/**
 * server-slice.js -- a real ElegooSlicer run through POST /api/slice.
 *
 *   node test/server-slice.js
 *
 * This actually launches C:\Program Files\ElegooSlicer\elegoo-slicer.exe.
 * It slices the 17 Pro model with that job's own profiles, into a temp dir
 * (NEVER into the job folder -- a slice is a proposal, not a version), and
 * checks the output against the G-code the same profiles produced before
 * (line for line -- the committed copy is CRLF in the working tree because
 * of core.autocrlf, see the reproducibility section).
 *
 * Also checks the two failure modes we know: a bad job name, and the -17
 * "profile not compatible" path by handing it the wrong machine profile.
 */
import './_isolate.js'; // must be first: keeps the tests out of the live bridge\ folder
import { readFile, writeFile, rm, mkdir, access } from 'node:fs/promises';
import path from 'node:path';
import { start, stop } from '../server/index.js';
import { ARCHIVE_ROOT, PROJECT_ROOT } from '../server/api/files.js';
import { ok, eq, section, row, run, post, PORT } from './server-helpers.js';

const SCRATCH = path.join(ARCHIVE_ROOT, 'gcode-studio-scratch-slice');
const REFERENCE = path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'old', 'EN4Max_0.4_Iphone17Pro_HexCover_HSPLA+_0.20_v1-ironed_49m.gcode');

await run(async () => {
  await rm(SCRATCH, { recursive: true, force: true });
  await mkdir(SCRATCH, { recursive: true });
  await start(PORT, '127.0.0.1');

  section('slice phonecase-17pro');
  const t0 = Date.now();
  const r = await post('/api/slice', { job: 'phonecase-17pro' });
  row('wall clock', (Date.now() - t0) + ' ms (including parse + validate)');
  row('slicer', r.ms + ' ms');
  row('exit code', `${r.exitCode}  ${r.meaning || ''}`);
  row('output', r.outPath);
  row('bytes', (r.bytes || 0).toLocaleString());
  if (r.stderr) row('stderr', r.stderr.slice(0, 300));

  ok(r.ok, 'the slice succeeded');
  eq(r.exitCode, 0, 'exit code 0');
  ok(r.ms < 30000, `slicer finished in ${r.ms} ms`);
  ok(/plate_1\.gcode$/.test(r.outPath || ''), 'output landed at plate_1.gcode');
  ok(!(r.outPath || '').includes('phonecase-17pro'), 'and NOT in the job folder');
  ok(!(await access(path.join(PROJECT_ROOT, '00000.log')).then(() => true, () => false)),
    'the slicer left no 00000.log in the project root');

  section('the sliced output');
  row('layers', r.meta.meta.layerCount);
  row('time', r.meta.meta.estimatedTimeText);
  row('filament', `${r.meta.meta.filamentUsedG} g / ${r.meta.meta.filamentUsedMm} mm`);
  row('moves', r.meta.count.toLocaleString());
  row('config keys', Object.keys(r.meta.config).length);
  eq(r.meta.meta.layerCount, 57, 'layer count matches the committed v1');
  eq(r.meta.meta.estimatedTimeText, '49m 15s', 'print time matches the committed v1');
  eq(r.meta.meta.filamentUsedG, 15.1, 'weight matches the committed v1');
  ok(r.meta.relativeE, 'the output uses M83 relative extrusion');

  section('validation of the sliced output');
  row('ok', String(r.validation.ok));
  for (const e of r.validation.errors) row('ERROR ' + e.code, e.message);
  for (const w of r.validation.warnings) row('warn ' + w.code, w.message);
  ok(r.validation.ok, 'freshly sliced G-code passes the validator');

  section('reproducibility');
  const stripDate = (s) => s.replace(/; generated by ElegooSlicer [\d.]+ on [\d-]+ at [\d:]+/, '; generated by <slicer> on <date>');
  // CRLF -> LF. Needed only because of how the reference file is checked out;
  // the comment above the committed-v1 comparison below has the measurement.
  const lf = (s) => s.replace(/\r\n/g, '\n');
  const configBlock = (s) => {
    const m = /^; CONFIG_BLOCK_START$([\s\S]*?)^; CONFIG_BLOCK_END$/m.exec(lf(s));
    const out = new Map();
    for (const line of (m ? m[1] : '').split('\n')) {
      const kv = /^; ([^=]+?) = ?(.*)$/.exec(line);
      if (kv) out.set(kv[1], kv[2]);
    }
    return out;
  };

  // The claim is about the slicer, so measure the slicer: slice the SAME inputs
  // a second time and compare the two outputs. This is the assertion that
  // actually carries "a re-slice is byte-identical given identical inputs".
  const t1 = Date.now();
  const again = await post('/api/slice', { job: 'phonecase-17pro' });
  row('second slice', `${Date.now() - t1} ms wall / ${again.ms} ms slicer`);
  ok(again.ok, 'a second slice of the same inputs succeeded');
  const fresh = await readFile(r.outPath, 'utf8');
  const twice = await readFile(again.outPath, 'utf8');
  row('fresh bytes', fresh.length.toLocaleString());
  row('second bytes', twice.length.toLocaleString());
  eq(twice.length, fresh.length, 'two slices of the same inputs are the same size');
  ok(stripDate(twice) === stripDate(fresh),
    'two slices of the same inputs are byte-identical once the generation timestamp is ignored');

  // Against the committed v1 the line endings have to be normalised first, and
  // that is a property of the checkout, not of the G-code. Measured 2026-09-19:
  //   fresh slice          2,963,504 bytes -- 124,722 LF, 0 CR
  //   working-tree v1      3,088,226 bytes -- 124,722 LF, 124,722 CR
  // exactly one extra byte per line. The repo has core.autocrlf=true and no
  // .gitattributes, and `git ls-files --eol` reports `i/lf w/crlf` for the file:
  // git rewrites LF -> CRLF on checkout. The committed blob itself
  // (`git show HEAD:demo/.../old/..._v1-ironed_49m.gcode`) is 2,963,504 bytes and
  // differs from a fresh slice on exactly ONE line, the `; generated by` stamp.
  // So the old raw-byte assertion was testing the reader's git config; it is
  // dropped in favour of the two-slice check above plus this normalised one.
  const committed = await readFile(REFERENCE, 'utf8');
  row('committed bytes', committed.length.toLocaleString());
  row('committed CR', ((committed.match(/\r/g) || []).length).toLocaleString() + ' CR bytes (checkout artefact)');
  const a = stripDate(lf(fresh)).split('\n');
  const b = stripDate(lf(committed)).split('\n');
  let differing = 0;
  const firstDiffs = [];
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    if (a[i] !== b[i]) {
      differing++;
      if (firstDiffs.length < 5) firstDiffs.push(`line ${i + 1}: fresh ${JSON.stringify(a[i])} vs v1 ${JSON.stringify(b[i])}`);
    }
  }
  row('differing lines', `${differing} of ${b.length}`);
  for (const d of firstDiffs) row('  diff', d.slice(0, 160));
  eq(a.length, b.length, 'same line count as the committed v1');
  eq(differing, 0, 'identical to the committed v1 line for line, timestamp and CRLF aside');

  // Independent of the whole-file compare: the settings the slicer baked in are
  // the ones the job's own three profiles asked for.
  const cfgFresh = configBlock(fresh);
  const cfgV1 = configBlock(committed);
  row('CONFIG_BLOCK keys', `${cfgFresh.size} fresh / ${cfgV1.size} committed`);
  ok(cfgFresh.size > 300, `the fresh CONFIG_BLOCK was found and parsed (${cfgFresh.size} keys)`);
  const cfgDiff = [...cfgV1].filter(([k, v]) => cfgFresh.get(k) !== v);
  for (const [k, v] of cfgDiff.slice(0, 10)) row('  cfg', `${k}: fresh ${JSON.stringify(cfgFresh.get(k))} vs v1 ${JSON.stringify(v)}`);
  eq(cfgDiff.length, 0, 'every CONFIG_BLOCK value matches the committed v1');

  section('error paths');
  const nope = await post('/api/slice', { job: 'does-not-exist' });
  eq(nope.__status, 404, 'unknown job -> 404');
  const noJob = await post('/api/slice', {});
  eq(noJob.__status, 400, 'missing job -> 400');
  const escape = await post('/api/slice', { job: '../../Windows' });
  ok(escape.__status === 403 || escape.__status === 404, `a job outside the Archive is refused (${escape.__status})`);

  section('exit -17: profile not compatible');
  // Two ways to provoke it, both documented in ..\..\context\slicing.md:
  // a process profile whose compatible_printers does not name this machine,
  // and a machine profile whose `name` is not exactly the expected string.
  const proc = JSON.parse(await readFile(path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'process.json'), 'utf8'));
  proc.compatible_printers = ['Some Other Printer 0.4 nozzle'];
  await writeFile(path.join(SCRATCH, 'process-bad.json'), JSON.stringify(proc, null, 1), 'utf8');
  const mach = JSON.parse(await readFile(path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'machine.json'), 'utf8'));
  mach.name = 'Wrong Name 0.4 nozzle';
  await writeFile(path.join(SCRATCH, 'machine-bad.json'), JSON.stringify(mach, null, 1), 'utf8');

  for (const [label, profiles] of [
    ['process compatible_printers wrong', { process: 'gcode-studio-scratch-slice/process-bad.json' }],
    ['machine name wrong', { machine: 'gcode-studio-scratch-slice/machine-bad.json' }],
  ]) {
    const bad = await post('/api/slice', { job: 'phonecase-17pro', profiles });
    row(label, `exit ${bad.exitCode} (raw ${bad.rawExitCode})  ${bad.meaning || '(unrecognised)'}`);
    row('  slicerLog', (bad.slicerLog || '(empty)').trim().slice(0, 140));
    ok((bad.slicerLog || '').includes('not compatible'), label + ': the slicer log is captured and says why');
    ok(!bad.ok, label + ': the slice fails rather than silently producing garbage');
    eq(bad.exitCode, -17, label + ': exit code normalised to signed -17');
    ok((bad.hint || '').includes('Elegoo Neptune 4 Max 0.4 nozzle'), label + ': the hint names the fix');
  }

  section('profiles outside the Archive tree');
  const outside = await post('/api/slice', {
    job: 'phonecase-17pro',
    profiles: { machine: process.env.APPDATA + '/ElegooSlicer/system/Elegoo/machine/EN4SERIES/x.json' },
  });
  eq(outside.__status, 403, 'refused -- the sandbox applies to profile paths too');

  await rm(r.outDir, { recursive: true, force: true });
  await rm(again.outDir, { recursive: true, force: true });
  await rm(SCRATCH, { recursive: true, force: true });
  await stop();
});
