/**
 * server-slice.js -- a real ElegooSlicer run through POST /api/slice.
 *
 *   node test/server-slice.js
 *
 * This actually launches C:\Program Files\ElegooSlicer\elegoo-slicer.exe.
 * It slices the 17 Pro model with that job's own profiles, into a temp dir
 * (NEVER into the job folder -- a slice is a proposal, not a version), and
 * checks the output against the G-code the same profiles produced before.
 *
 * Also checks the two failure modes we know: a bad job name, and the -17
 * "profile not compatible" path by handing it the wrong machine profile.
 */
import './_isolate.js'; // must be first: keeps the tests out of the live bridge\ folder
import { readFile, writeFile, rm, mkdir, access } from 'node:fs/promises';
import path from 'node:path';
import { start, stop } from '../server/index.js';
import { ARCHIVE_ROOT, PROJECT_ROOT } from '../server/api/files.js';
import { ok, eq, section, row, run, post, PORT } from './server-helpers.js';

const SCRATCH = path.join(ARCHIVE_ROOT, 'gcode-studio-scratch-slice');
const REFERENCE = path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'old', 'EN4Max_0.4_Iphone17Pro_HexCover_HSPLA+_0.20_v1-ironed_49m.gcode');

await run(async () => {
  await rm(SCRATCH, { recursive: true, force: true });
  await mkdir(SCRATCH, { recursive: true });
  await start(PORT, '127.0.0.1');

  section('slice phonecase-17pro');
  const t0 = Date.now();
  const r = await post('/api/slice', { job: 'phonecase-17pro' });
  row('wall clock', (Date.now() - t0) + ' ms (including parse + validate)');
  row('slicer', r.ms + ' ms');
  row('exit code', `${r.exitCode}  ${r.meaning || ''}`);
  row('output', r.outPath);
  row('bytes', (r.bytes || 0).toLocaleString());
  if (r.stderr) row('stderr', r.stderr.slice(0, 300));

  ok(r.ok, 'the slice succeeded');
  eq(r.exitCode, 0, 'exit code 0');
  ok(r.ms < 30000, `slicer finished in ${r.ms} ms`);
  ok(/plate_1\.gcode$/.test(r.outPath || ''), 'output landed at plate_1.gcode');
  ok(!(r.outPath || '').includes('phonecase-17pro'), 'and NOT in the job folder');
  ok(!(await access(path.join(PROJECT_ROOT, '00000.log')).then(() => true, () => false)),
    'the slicer left no 00000.log in the project root');

  section('the sliced output');
  row('layers', r.meta.meta.layerCount);
  row('time', r.meta.meta.estimatedTimeText);
  row('filament', `${r.meta.meta.filamentUsedG} g / ${r.meta.meta.filamentUsedMm} mm`);
  row('moves', r.meta.count.toLocaleString());
  row('config keys', Object.keys(r.meta.config).length);
  eq(r.meta.meta.layerCount, 57, 'layer count matches the committed v1');
  eq(r.meta.meta.estimatedTimeText, '49m 15s', 'print time matches the committed v1');
  eq(r.meta.meta.filamentUsedG, 15.1, 'weight matches the committed v1');
  ok(r.meta.relativeE, 'the output uses M83 relative extrusion');

  section('validation of the sliced output');
  row('ok', String(r.validation.ok));
  for (const e of r.validation.errors) row('ERROR ' + e.code, e.message);
  for (const w of r.validation.warnings) row('warn ' + w.code, w.message);
  ok(r.validation.ok, 'freshly sliced G-code passes the validator');

  section('reproducibility');
  const fresh = await readFile(r.outPath, 'utf8');
  const committed = await readFile(REFERENCE, 'utf8');
  row('fresh bytes', fresh.length.toLocaleString());
  row('committed bytes', committed.length.toLocaleString());
  const stripDate = (s) => s.replace(/; generated by ElegooSlicer [\d.]+ on [\d-]+ at [\d:]+/, '; generated by <slicer> on <date>');
  ok(stripDate(fresh) === stripDate(committed),
    'byte-identical to the committed v1 once the generation timestamp is ignored');

  section('error paths');
  const nope = await post('/api/slice', { job: 'does-not-exist' });
  eq(nope.__status, 404, 'unknown job -> 404');
  const noJob = await post('/api/slice', {});
  eq(noJob.__status, 400, 'missing job -> 400');
  const escape = await post('/api/slice', { job: '../../Windows' });
  ok(escape.__status === 403 || escape.__status === 404, `a job outside the Archive is refused (${escape.__status})`);

  section('exit -17: profile not compatible');
  // Two ways to provoke it, both documented in ..\..\context\slicing.md:
  // a process profile whose compatible_printers does not name this machine,
  // and a machine profile whose `name` is not exactly the expected string.
  const proc = JSON.parse(await readFile(path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'process.json'), 'utf8'));
  proc.compatible_printers = ['Some Other Printer 0.4 nozzle'];
  await writeFile(path.join(SCRATCH, 'process-bad.json'), JSON.stringify(proc, null, 1), 'utf8');
  const mach = JSON.parse(await readFile(path.join(ARCHIVE_ROOT, 'phonecase-17pro', 'machine.json'), 'utf8'));
  mach.name = 'Wrong Name 0.4 nozzle';
  await writeFile(path.join(SCRATCH, 'machine-bad.json'), JSON.stringify(mach, null, 1), 'utf8');

  for (const [label, profiles] of [
    ['process compatible_printers wrong', { process: 'gcode-studio-scratch-slice/process-bad.json' }],
    ['machine name wrong', { machine: 'gcode-studio-scratch-slice/machine-bad.json' }],
  ]) {
    const bad = await post('/api/slice', { job: 'phonecase-17pro', profiles });
    row(label, `exit ${bad.exitCode} (raw ${bad.rawExitCode})  ${bad.meaning || '(unrecognised)'}`);
    row('  slicerLog', (bad.slicerLog || '(empty)').trim().slice(0, 140));
    ok((bad.slicerLog || '').includes('not compatible'), label + ': the slicer log is captured and says why');
    ok(!bad.ok, label + ': the slice fails rather than silently producing garbage');
    eq(bad.exitCode, -17, label + ': exit code normalised to signed -17');
    ok((bad.hint || '').includes('Elegoo Neptune 4 Max 0.4 nozzle'), label + ': the hint names the fix');
  }

  section('profiles outside the Archive tree');
  const outside = await post('/api/slice', {
    job: 'phonecase-17pro',
    profiles: { machine: process.env.APPDATA + '/ElegooSlicer/system/Elegoo/machine/EN4SERIES/x.json' },
  });
  eq(outside.__status, 403, 'refused -- the sandbox applies to profile paths too');

  await rm(r.outDir, { recursive: true, force: true });
  await rm(SCRATCH, { recursive: true, force: true });
  await stop();
});
